name: Manual ppn-page Update (Simple)

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Trigger ppn-page update
        env:
          GITHUB_TOKEN: ${{ secrets.PPN_PAGE_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dkurokawa/ppn-page/dispatches \
            -d '{"event_type":"project-update","client_payload":{"repository":"vscode-web-panel","version":"v0.4.0"}}'